### ISSUE TITLE
[FEATURE_REQUEST] Feature to track pages

### ISSUE THREAD

**Issue by chromer030** [mateusz-bak/openreads-android#226] opened 2023-03-01 10:08 UTC
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Please add a feature to track how many pages are read and how many left to finish.

**Describe alternatives you've considered**

**Additional context**

**Comment by Black-StellarSpectrum** [comment] 2023-06-25 22:47
Yup I came here to ask for this feature, for In progress books it's nice to have page tracker which can be directly editable via In progress tab (like Showly)

**Comment by Amolith** [comment] 2023-07-29 16:43
It would also be nice if it could track percentage rather than just page count; eBooks with reflowed text don't have page counts that match up with the printed version.

**Comment by apobrt** [comment] 2023-09-05 13:12
Duplicate of #61

**Closed by apobrt** 2023-09-05 13:12 UTC
Labels: duplicate, enhancement
