### ISSUE TITLE
[BUG] Can't restore backup

### ISSUE THREAD

**Issue by SkyAzul91** [mateusz-bak/openreads-android#318] opened 2023-08-22 03:14 UTC
I wanted to restore my data to my new phone which has android 12 (my last phone had android 13), but when I tap on restore backup, an Openreads file manager opens and my backup is nowhere to be found. No files are shown, just the folders. I would really appreciate a fix for this problem, I have been waiting for it to be fixed for a while, but I thought it best to report it. Thank you for such a great app.

**Comment by SkyAzul91** [comment] 2023-08-24 01:37
Hii

1. You will laugh, haahsd. Is a Tecno Spark Go 2023, with android 12. I think is an android thing, because I have seen other reports of this problem on android 12 and below, and on my previous samsung with android 13 this does not happen, I can open the phone's file manager without any problem, it does not open any other that the phone doesn't have.

2. Is: Openreads-4-2.0.3-2023_7_24-21_47_26.backup

3. Downloads.

4. Sure! Give me a minute.

**Comment by SkyAzul91** [comment] 2023-08-24 01:51
I sent you to your gmail the video, the name of the email is "[BUG] Can't restore backup video"

**Comment by vodknuckles** [comment] 2023-08-30 03:42
This is a duplicate of #246 and has been quite a large issue for months at this point.

**Comment by apobrt** [comment] 2023-09-05 13:58
Yes, we close this as a duplicate.
We definitely have to fix this bug

**Closed by apobrt** 2023-09-05 13:58 UTC
Labels: bug
