### ISSUE TITLE
Privacy issue: requests to openlibrary.org via HTTP instead of HTTPS

### ISSUE THREAD

**Issue by j-lakeman** [mateusz-bak/openreads-android#416] opened 2023-12-22 16:19 UTC
**Describe the bug**
If searching for a book, the requests seem to be made via the insecure HTTP protocol.

**To Reproduce**
Monitor DNS traffic using an app like NetGuard or Rethink DNS. Find Openreads after searching for a book.

**Expected behavior**
HTTPS requests instead

**Comment by apobrt** [comment] 2024-01-02 10:39
Duplicate of https://github.com/mateusz-bak/openreads-android/issues/405

**Closed by apobrt** 2024-01-02 10:39 UTC
Labels: bug
