### ISSUE TITLE
[BUG] App regularly shows intro screens

### ISSUE THREAD

**Issue by DSiekmeier** [mateusz-bak/openreads-android#255] opened 2023-04-10 11:12 UTC
**Describe the bug**
From time to time OpenReads shows the introduction screens / tutorial when starting the app.

**To Reproduce**
Not sure yet.

**Expected behavior**
Show tutorial only on first start of the app / after an update.

**Screenshots**
Tbd.

**Additional info(please complete the following information):**
 - Huawei P30 Lite 
 - Android version: Emui 12
 - App version: 2.0.3
 - App source: F-Droid

**Additional context**
TBD.

**Comment by mateusz-bak** [comment] 2023-04-18 20:21
Closing as duplicate of #227

**Closed** 2023-04-18 20:21 UTC
Labels: bug
