### ISSUE TITLE
[BUG] Openreads 4 Restore Backup file manager not showing files

### ISSUE THREAD

**Issue by brucetheelephant** [mateusz-bak/openreads-android#246] opened 2023-03-19 22:02 UTC
**Describe the bug**
The Openreads 4 Restore Backup file manager does not show any files when browsing. When I go to my backup folder it is empty, when I go to a folder where there should be photos or screenshots (for example) it is also empty. Correction: These are SHOWING empty. When I browse these folders with other file managers (like (Google's) Files or Simple File Manager) they are showing the containing files.

**To Reproduce**
1. Start the Restore Backup process. 
2. Browse with the Openreads 4 file manager

**Expected behavior**
I expected to see and be able to load and restore backup files.

**Screenshots**
If I have to I can upload some.

**Additional info(please complete the following information):**
 - Manufacturer and model: Xiaomi Redmi Note 10T 5G
 - Android version: 11 RKQ1.210327.001
 - MIUI version: MIUI Global 13.0.9 Stable
 - App version: 2.0.3
 - App source (F-Droid, Google Play, Github): Github

**Additional context**
Can this be a Permission thing!? I the System Settings / Permission Manager / Files And Media I have two sections: Allowed To Manage All Files and Allowed Access To Media Only. Openreads 4 is in the second section. There is no way (that I can see) to move it to the first section. But even so I should at least be able to see media files in folders ..

**Comment by mateusz-bak** [comment] 2023-03-20 22:44
Thanks for reporting that. I guess MIUI's heavy system modifications might cause trouble here. Did you do a fresh install or updated from some other version? I will setup a Android 11 emulator to test this out anyway.

**Comment by vodknuckles** [comment] 2023-06-29 14:14
> Thanks for reporting that. I guess MIUI's heavy system modifications might cause trouble here. Did you do a fresh install or updated from some other version? I will setup a Android 11 emulator to test this out anyway.

I have a Google Pixel 3 XL with Android 11 and I can confirm the same exact issue on version 2.0.3.

If you navigate to Settings > Backup and Restore > Restore Backup, you'll see the screen below, but none of the folders will have any visible files in them. It seems the app is using it's own file explorer (?) instead of the built-in Android one.

I have a large amount of Google's apps removed from my phone however. Perhaps the app is depending on some Google app to display files? Other apps with similar file-picking features have no issue using the built-in file explorer on my phone though.

![Screenshot_20230629-100306](https://github.com/mateusz-bak/openreads-android/assets/51679213/20991fbc-1368-40ef-a417-471707e89176)

**Comment by vodknuckles** [comment] 2023-06-29 14:17
> > Thanks for reporting that. I guess MIUI's heavy system modifications might cause trouble here. Did you do a fresh install or updated from some other version? I will setup a Android 11 emulator to test this out anyway.
> 
> I have a Google Pixel 3 XL with Android 11 and I can confirm the same exact issue on version 2.0.3.
> 
> If you navigate to Settings > Backup and Restore > Restore Backup, you'll see the screen below, but none of the folders will have any visible files in them. It seems the app is using it's own file explorer (?) instead of the built-in Android one.
> 
> I have a large amount of Google's apps removed from my phone however. Perhaps the app is depending on some Google app to display files? Other apps with similar file-picking features have no issue using the built-in file explorer on my phone though.
> 
> ![Screenshot_20230629-100306](https://user-images.githubusercontent.com/51679213/249795695-20991fbc-1368-40ef-a417-471707e89176.png)

My Google Pixel 5 with Android 13 on app version 2.0.3 does not have this issue and uses the built-in file explorer to find backup files without issue.

**Comment by vodknuckles** [comment] 2023-06-29 14:17
My Google Pixel 5 with Android 13 on app version 2.0.3 does not have this issue and uses the built-in file explorer to find backup files without issue.

**Comment by vodknuckles** [comment] 2023-07-01 00:18
Just factory reset my Pixel 3 (different from the first one, also Android 11) and the same problem happened. I installed the latest version (2.0.3) of the app from F-Droid, went to the Restore Backup section, pressed Yes, and was dumped into an Android 13 looking file picker and was unable to find any backup files.

**Comment by mateusz-bak** [comment] 2023-09-20 20:50
@vodknuckles @brucetheelephant It may be the issue with Android 11 then. Android's file permissions are changed each version so that causes some troubles. I will take  a look at it now in Android 11. And unfortunately I cannot add the manage all files permission (blocked by Google for non file explorers).

**Comment by mateusz-bak** [comment] 2023-09-21 09:48
@brucetheelephant I have Android 13 and the app uses the default file explorer. I think I implemented that way as a workaround for older Android versions. I'm taking a look today why it is implemented like that.

**Comment by mateusz-bak** [comment] 2023-09-26 21:27
I think I made a mistake when app chooses legacy/current way of handling phone's storage. I corrected it now and you will be able to check if that's fixed in 2.2 release.

**Comment by vodknuckles** [comment] 2023-10-03 17:44
I found a strange workaround for my device in the meantime.

After pressing the "Restore backup" option, I noticed that the only filetype that shows up is .png. so I renamed the backup file on my phone that I couldn't import earlier to "Openreads-XXX...backup.png" and attempted to import it in the app as if it were a backup file. The app hanged for a few seconds, I closed it and reopened it, and the import was successful and it displayed all of my books and statistics as expected.

The only thing that I noticed was missing was my yearly book / page goal, but I think that was due to the newest update. Cheers!

**Comment by mateusz-bak** [comment] 2023-10-05 19:43
@vodknuckles glad it worked somehow :D

**Comment by mateusz-bak** [comment] 2023-11-13 22:12
I'm starting to release 2.2.0 version. When you test it let me know if there are any issues and reopen the ticket.

Just to be clear on how this is fixed - this will work correctly with backup files created since version 2.2.0. Previous backups should be loaded with the mentioned workaround and re-created in the new version.

**Closed by mateusz-bak** 2023-11-13 22:12 UTC
Labels: bug, waiting for release
