### ISSUE TITLE
[BUG] Unresponsive "Add Book" Options 

### ISSUE THREAD

**Issue by JuanSH11** [mateusz-bak/openreads-android#381] opened 2023-11-26 04:53 UTC
**Description**
The app provides multiple methods to add books to the user's collection. However, these options
are currently not functioning, thereby preventing users from expanding their collection.

**To Reproduce**
• Launch the app.
• Attempt to use the various options to add books (manual entry, barcode scanning, or
search).

**Expected behavior**
All the methods provided for adding books should be operational, allowing users to add books
manually, through barcode scanning, or by searching.

**Device**
• Processor: Equipped with a powerful octa-core processor, providing a balance of energy
efficiency and performance, ideal for demanding applications.
• RAM: Comes with 4GB/6GB RAM options, facilitating efficient multitasking and smooth
operation of resource-intensive tasks.
• Storage: Offers 64GB/128GB internal storage options, expandable via microSD, ensuring
ample space for app data and cache without compromising performance.
• Display: Features a Full HD+ Super AMOLED display, delivering crisp and vibrant visuals,
which is crucial for analyzing graphical elements of the app.
• Battery Life: Powered by a robust 5000mAh battery, allowing for extensive use and testing
without frequent recharging, essential for long-term performance evaluation.
• Operating System: Runs on the latest version of Android, providing a modern software
environment for app compatibility and performance testing.
• Network Connectivity: Supports 4G LTE, enabling fast data transfer rates which are vital
for testing network-dependent features of the app.

**Comment by mateusz-bak** [comment] 2023-11-26 13:40
Duplicate of https://github.com/mateusz-bak/openreads-android/issues/298

We tried to reproduce the issue to fix it but could not unfortunately. If you have any info that will help us reproduce please add into the linked ticket.

However in https://github.com/mateusz-bak/openreads-android/issues/382 you noted issues with barcode scanning so I suppose the button to add book worked?

**Closed** 2023-11-26 13:40 UTC
Labels: bug
