### ISSUE TITLE
[FEATURE_REQUEST] Add Android Material You icon

### ISSUE THREAD

**Issue by Darkempire78** [mateusz-bak/openreads-android#146] opened 2022-09-05 05:11 UTC
**Describe the solution you'd like**
https://developer.android.com/develop/ui/views/launch/icon_design_adaptive
Since android 13, icons should follow Material You

**Comment by apobrt** [comment] 2023-08-29 18:32
Seems a duplicate of #284

**Comment by apobrt** [comment] 2023-09-05 09:50
Close as duplicate

**Closed by apobrt** 2023-09-05 09:50 UTC
Labels: duplicate, enhancement
