### ISSUE TITLE
[BUG] App settings resets after clearing the RAM cache

### ISSUE THREAD

**Issue by chromer030** [mateusz-bak/openreads-android#227] opened 2023-03-02 10:57 UTC
**Describe the bug**
My phone has a shortcut to clear the RAM cache , and every time i clear the RAM cache , openreads settings resets and welcome screen will be shown ! 

**To Reproduce**
- Launch the app and change the settings.
- clear your smartphone RAM cache
- relaunch the app

**Expected behavior**

**Screenshots**

**Additional info(please complete the following information):**
 - Manufacturer and model: Lenovo
 - Android version: 7.1.2
 - App version: v2.0.0-rc3
 - App source (F-Droid, Google Play, Github): Github Release

**Additional context**

**Comment by mateusz-bak** [comment] 2023-03-02 11:09
Hi, does it also affect other settings like language, visuals, sorting type etc? Did you have this issues with version 1.17?

**Comment by chromer030** [comment] 2023-03-02 11:14
Hi, Version 1.17 is OK , It resets whatever in setting : font, color etc.

**Comment by mateusz-bak** [comment] 2023-03-14 10:39
Please attach screenshot /video of the clear RAM functionality. The data you mentioned is not stored in RAM but on the device storage. I need to understand what's going on there

**Comment by chromer030** [comment] 2023-03-18 10:50
https://user-images.githubusercontent.com/13361552/226100856-4c3e84be-45d2-4da3-86f5-a76f6ac50420.mp4

**Comment by exstntlmsnthrp** [comment] 2023-03-18 14:19
Apps like that often "clean" application cache in addition to memory cache, amongst many other things that users don't realize. Not to mention, they don't often provide the actual benefits they claim they do. Cleaning memory cache has been proven to be pointless many times over the years. As soon as you begin using apps on the phone, the cache fills up again. 

Have you confirmed what the settings are in the cleaner app before assuming the problem is openreads?

This has only ever happened with me when I cleared the application cache (which I did intentionally) for openreads, which is held in phone storage, like @mateusz-bak noted in their response.

**Comment by chromer030** [comment] 2023-03-18 16:34
This app is build-in to ROM and doesn't clean application cache , it just clean memory cache.

I assume the problem is in openreads and the way it's storing the settings , because among 200 app i have and use most of them , just openreads has this issue.

**Comment by mateusz-bak** [comment] 2023-04-18 20:23
I think this was caused by wrong placement of app's preferences storage directory. Added a change in #259 

Closing for now, will be released in 2.0.4 version this week. Please reopen if issue will persist.

**Closed by mateusz-bak** 2023-04-18 20:23 UTC
Labels: bug
