### ISSUE TITLE
[BUG] App crashes when adding new books on 1.17.0

### ISSUE THREAD

**Issue by exstntlmsnthrp** [mateusz-bak/openreads-android#159] opened 2022-10-17 20:02 UTC
**Describe the bug**
I upgraded from 1.16.0 to 1.17.0 and app crashes when trying to add new books.

**To Reproduce**
Download 1.17.0 from GitHub. Update app. Click "+" button to add a new book. Select any option. When adding manually or when searching in Open Library, app crashes before you can fully enter information. When attempting to scan barcode, app crashes before being able to scan barcode.

**Expected behavior**
Adding a book by any method should result in the book being added to the collection.

**Screenshots**
Unable to get screenshot because the app keeps crashing.

**Additional info(please complete the following information):**
 - Manufacturer and model: Pixel 7 Pro
 - Android version: 13
 - App version: see above
 - App source (F-Droid, Google Play, Github): GitHub 

After downgrading back to version 1.16.0, the app works as normal.

By the way, I love this app! It's the best of any app like this I've found and is very helpful. I have over 2000 books and this makes managing then very easy. I also really like the UI! Thanks devs!

**Comment by exstntlmsnthrp** [comment] 2022-10-17 21:14
@mateusz-bak Thank you for the very fast reply (and for the brilliant app).

Let me install the new version again to try and answer your follow up questions.

Yes, I was able to create the backup before I removed the 1.17.0 version the first time

**Comment by exstntlmsnthrp** [comment] 2022-10-17 21:21
Okay. I installed 1.17.0 again. I can click and view existing books in the library and I can edit items related to existing books.

It will only crash when I attempt to add new books. I'm not a developer by any means, but my first guess would be to look at how the new version is interacting with Open Library. The app will only crash when trying to search Open Library - manually or by scanning.

I hope this helps.

**Comment by mateusz-bak** [comment] 2022-10-17 21:56
Okay I spotted crashes after searching in Open Library and deleting a book. Will try to prepare a fix tomorrow.

**Comment by mateusz-bak** [comment] 2022-10-18 20:12
@exstntlmsnthrp 

I reverted some changes from 1.17.0 release. Could not reproduce the issue unfortunately on my debugging setup so can you test 1.17.1-rc1?

 ### Please take a backup of your books first and save the in a safe location (cloud probably).

Here is the link for the 1.17.1-rc1 version: https://github.com/mateusz-bak/openreads-android/releases/tag/1.17.1-rc1

I don't want to spend a lot of time on debugging this version as I'm making a good progress with the Flutter app.

Let me know if this release fixes those issues!

**Comment by exstntlmsnthrp** [comment] 2022-10-18 20:28
Thank you! I will test it when I'm home. I saved both local and cloud backup, so I'm fine there.

Honestly, I'm happy to hear that progress with the Flutter app is going well. I'd rather you put your energy and time into that. If this doesn't work, I'll just use 1.16.0 until you release the Flutter app.

**Comment by exstntlmsnthrp** [comment] 2022-10-18 22:25
Okay, whatever you did seems to have resolved the problem for me. The testing build doesn't crash like 1.17.0.

Cheers. I look forward to seeing the new app in flutter.

**Comment by mateusz-bak** [comment] 2022-10-19 20:21
1.17.1 released with the fix, please re-open the ticket if crashes still occur.

**Closed by mateusz-bak** 2022-10-19 20:21 UTC
Labels: bug, work in progress
