### ISSUE TITLE
[BUG] Screen Size Reduction After Barcode Scan

### ISSUE THREAD

**Issue by JuanSH11** [mateusz-bak/openreads-android#382] opened 2023-11-26 04:54 UTC
**Description**
After certain actions within the app, especially related to barcode scanning, the available screen size
is reduced. While the content remains accessible through scrolling, the truncated view hinders the
user experience.

**To Reproduce**
• Launch the app.
• Click on the "+" button to add a new book.
• Opt to add a book using the barcode scanner.
• After scanning:
• If a book is identified, both the "Choose Edition" and "Add Book" actions will result
in the screen size reduction.
• If no book is found, navigating back will similarly reduce the screen size.
• In both instances, returning to the previous screen does not reset the screen size

**Expected behavior**
The application's screen size should remain consistent across all functionalities and actions, ensuring
a seamless user experience.

**Device**
• Processor: Equipped with a powerful octa-core processor, providing a balance of energy
efficiency and performance, ideal for demanding applications.
• RAM: Comes with 4GB/6GB RAM options, facilitating efficient multitasking and smooth
operation of resource-intensive tasks.
• Storage: Offers 64GB/128GB internal storage options, expandable via microSD, ensuring
ample space for app data and cache without compromising performance.
• Display: Features a Full HD+ Super AMOLED display, delivering crisp and vibrant visuals,
which is crucial for analyzing graphical elements of the app.
• Battery Life: Powered by a robust 5000mAh battery, allowing for extensive use and testing
without frequent recharging, essential for long-term performance evaluation.
• Operating System: Runs on the latest version of Android, providing a modern software
environment for app compatibility and performance testing.
• Network Connectivity: Supports 4G LTE, enabling fast data transfer rates which are vital
for testing network-dependent features of the app.

**Comment by mateusz-bak** [comment] 2023-11-26 13:37
Duplicate of https://github.com/mateusz-bak/openreads-android/issues/254

We tried to reproduce the issue to fix it but could not unfortunately. If you have any info that will help us reproduce please add into the linked ticket.

**Closed by mateusz-bak** 2023-11-26 13:37 UTC
Labels: bug
